version: "3.9"

services:

  auth:
    build:
      dockerfile: Dockerfile
      context: ./../auth
      target: development
    image: skn1942/ftgo-auth
    ports:
      - 9991:9991
    expose:
      - 9991
    command: npm run start:dev
    environment:
      - MONGO_HOST=auth-mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=auth
      - NATS_URL=nats://nats-server:4222
    volumes:
      - ./../auth:/usr/src/app
    depends_on:
      - auth-mongodb
      - nats-server

  auth-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - auth-data

  restaurant:
    build:
      context: ./../restaurant
      dockerfile: Dockerfile
      target: development
    image: skn1942/ftgo-restaurant
    ports:
      - 9993:9993
    expose:
      - 9993
    command: npm run start:dev
    environment:
      - POSTGRES_DB=restaurant-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=restaurant-pg
      - POSTGRES_PORT=5432
      - NATS_URL=nats://nats-server:4222
    volumes:
      - ./../restaurant:/usr/src/app
    depends_on:
      - restaurant-pg
      - nats-server

  restaurant-pg:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=restaurant-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - restaurant-data:/var/lib/postgresql/data/

  cart:
    build:
      context: ./../cart
      dockerfile: Dockerfile
      target: development
    image: skn1942/ftgo-cart
    ports:
      - 9994:9994
    expose:
      - 9994
    command: >
      sh -c "npx prisma migrate dev --skip-generate --name init && npm run start:dev"
    environment:
      - POSTGRES_DB=cart-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=cart-pg
      - POSTGRES_PORT=5432
      - NATS_URL=nats://nats-server:4222
    volumes:
      - ./../cart:/usr/src/app
    depends_on:
      - cart-pg
      - nats-server
  cart-pg:
    image: postgres
    ports:
      - 5433:5432
    expose:
      - 5433
    environment:
      - POSTGRES_DB=cart-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - cart-data:/var/lib/postgresql/data/

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./../gateway
      target: development
    image: skn1942/ftgo-gateway
    ports:
      - 9992:9992
    expose:
      - 9992
    command: npm run start:dev
    volumes:
      - ./../gateway:/usr/src/app
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=9991
      - RESTAURANT_HOST=restaurant
      - RESTAURANT_PORT=9993
      - CART_HOST=cart
      - CART_PORT=9994
      - ORDER_HOST=order
      - ORDER_PORT=9995
    depends_on:
      - auth
      - restaurant
      - cart

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    expose:
      - 4222
    command: -c nats-server.conf -DV

volumes:
  auth-data:
  restaurant-data:
  cart-data:
  order-data:
