version: "3.9"

services:

  ftgo-auth:
    build:
      dockerfile: Dockerfile
      context: ./../auth
      target: development
    image: skn1942/ftgo-auth
    ports:
      - 9991:9991
    expose:
      - 9991
    command: npm run start:dev
    environment:
      - MONGO_HOST=auth-mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=auth
      - NATS_URL="nats://nats-server:4222"
    volumes:
      - ./../auth:/usr/src/app
    depends_on:
      - auth-mongodb
      - nats-server

  auth-mongodb:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - auth-data

  ftgo-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: skn1942/ftgo-restaurant
    ports:
      - 9993:9993
    expose:
      - 9993
    command: npm run start:dev
    environment:
      - POSTGRES_DB=ftgo-restaurant-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=restaurant-pg
      - POSTGRES_PORT=5432
    volumes:
      - ./:/usr/src/app
    depends_on:
      - restaurant-pg
      - nats-server
      - ftgo-auth

  restaurant-pg:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=ftgo-restaurant-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - restaurant-data:/var/lib/postgresql/data/

  ftgo-gateway:
    build:
      context: ./../gateway
      dockerfile: Dockerfile
      target: development
    image: skn1942/ftgo-gateway
    ports:
      - 9992:9992
    expose:
      - 9992
    command: npm run start:dev
    volumes:
      - ./../gateway:/usr/src/app
    depends_on:
      - ftgo-auth
      - ftgo-restaurant

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    expose:
      - 4222
    command: -c nats-server.conf -DV
  # another:
  #   image: python:3.5.2
  #   container_name: another
  #   entrypoint: /usr/bin/yes

volumes:
  auth-data:
  restaurant-data:
