apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/auth/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 9991
          - path: /api/gateway/?(.*)
            backend:
              serviceName: gateway-srv
              servicePort: 9992
          - path: /api/restaurant/?(.*)
            backend:
              serviceName: restaurant-srv
              servicePort: 9993
          - path: /api/cart/?(.*)
            backend:
              serviceName: cart-srv
              servicePort: 9994
