name: tests-restaurant

on: 
  pull_request:
    paths:
      - 'restaurant/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd auth && yarn && yarn run test
