name: tests-order

on: 
  pull_request:
    paths:
      - 'order/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd order && yarn && yarn run test
